# echo "DATABASE_URL: $FEATURE_DATABASE_URL" >> env.yml
echo "DATABASE_URL: $FEATURE_DATABASE_URL" >> env.yml
echo "DEPLOY_ENVIRON: FEATURE" >> env.yml
echo "DJANGO_AWS_STORAGE_BUCKET_NAME: $DJANGO_AWS_STORAGE_BUCKET_NAME_DEV_MEDIA" >> env.yml
echo "DJANGO_AWS_STORAGE_BUCKET_NAME_STATIC: $DJANGO_AWS_STORAGE_BUCKET_NAME_DEV_STATIC" >> env.yml