echo "GIT_BRANCH: $CI_COMMIT_REF_NAME" >> env.yml
echo "GIT_REPO: $CI_REPOSITORY_URL" >> env.yml

echo "CUSTOMER_CODE: $CUSTOMER_CODE" >> env.yml
echo "PROJECT_CODE: $PROJECT_CODE" >> env.yml
echo "DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE" >> env.yml
echo "ADMIN_EMAIL: $ADMIN_EMAIL" >> env.yml
echo "DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS" >> env.yml
echo "SENTRY_DSN: $SENTRY_DSN" >> env.yml
echo "DJANGO_DEBUG: $DJANGO_DEBUG" >> env.yml
echo "DJANGO_AWS_ACCESS_KEY_ID: $DJANGO_AWS_ACCESS_KEY_ID" >> env.yml
echo "DJANGO_AWS_SECRET_ACCESS_KEY: $DJANGO_AWS_SECRET_ACCESS_KEY" >> env.yml
