
---

- name: Setup the Git repo
  git: repo={{ git_repo }}
       version={{ git_branch }}
       dest={{ project_path }}
       accept_hostkey=yes
       force=yes
       update=yes
  become_user: "{{ gunicorn_user }}"
  tags: git



