
- name: Copy the gunicorn service file
  template:
    src: systemd_service.j2
    dest: "/etc/systemd/system/{{ project_code }}.service"

- name: restart gunicorn service
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ project_code }}"
    enabled: yes

