
# ---

gunicorn_num_workers: 3
gunicorn_timeout_seconds: 6000

# Setting this to 1 will restart the Gunicorn process each time
# you make a request, basically reloading the code. Very handy
# when developing. Set to 0 for unlimited requests (default).
gunicorn_max_requests: 0


# # Virtualenv settings.
# enable_deadsnakes_ppa: no
recreate_virtualenv: no
# virtualenv_python_version: "{{ base_python_package }}"


# # Application settings.
# aws_username: ubuntu
# virtualenv_path: "venvs/jfwagtailenv"
# project_path: "jfwatail"
# application_log_dir: "home/{{ aws_username }}/logs"
# application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
# requirements_file: "{{ project_path }}/requirements.txt"


# # Gunicorn settings.
# gunicorn_user: ubuntu
# gunicorn_group: ubuntu


# # Nginx settings.
# nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
# nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
# nginx_static_dir: "{{ virtualenv_path }}/static/"
# nginx_media_dir: "{{ virtualenv_path }}/media/"


run_django_collectstatic: yes
# # Django environment variables.
# django_environment:
#   DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
#   DJANGO_SECRET_KEY: "{{ django_secret_key }}"
#   MEDIA_ROOT: "{{ nginx_media_dir }}"
#   STATIC_ROOT: "{{ nginx_static_dir }}"
#   DATABASE_NAME: "{{ db_name }}"
#   DATABASE_USER: "{{ db_user }}"
#   DATABASE_PASSWORD: "{{ db_password }}"
#   BROKER_URL: "{{ broker_url }}"

